// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("BOQEntry")]
    public partial class Boqentry
    {
        public int Id { get; set; }
        public int? MatId { get; set; }
        public int? Qty { get; set; }
        public int? SitedId { get; set; }

        [ForeignKey("MatId")]
        [InverseProperty("Boqentries")]
        public virtual Material Mat { get; set; }
        [ForeignKey("SitedId")]
        [InverseProperty("Boqentries")]
        public virtual Site Sited { get; set; }
    }
}