// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("BOQSetup")]
    public partial class Boqsetup
    {
        public int Id { get; set; }
        public int MatId { get; set; }
        public int? Quantifier { get; set; }
        public int? ParentMatId { get; set; }

        [ForeignKey("MatId")]
        [InverseProperty("BoqsetupMats")]
        public virtual Material Mat { get; set; }
        [ForeignKey("ParentMatId")]
        [InverseProperty("BoqsetupParentMats")]
        public virtual Material ParentMat { get; set; }
    }
}