// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("Client")]
    public partial class Clients
    {
        public Clients()
        {
            ProjectMasters = new HashSet<ProjectMaster>();
        }

        public int Id { get; set; }
        public string BusinessName { get; set; }
        public string Shortname { get; set; }

        [InverseProperty("Client")]
        public virtual ICollection<ProjectMaster> ProjectMasters { get; set; }
    }
}