// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    public partial class Material
    {
        public Material()
        {
            Boqentries = new HashSet<Boqentry>();
            BoqsetupMats = new HashSet<Boqsetup>();
            BoqsetupParentMats = new HashSet<Boqsetup>();
            ProjectMaterials = new HashSet<ProjectMaterial>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }

        [InverseProperty("Mat")]
        public virtual ICollection<Boqentry> Boqentries { get; set; }
        [InverseProperty("Mat")]
        public virtual ICollection<Boqsetup> BoqsetupMats { get; set; }
        [InverseProperty("ParentMat")]
        public virtual ICollection<Boqsetup> BoqsetupParentMats { get; set; }
        [InverseProperty("Material")]
        public virtual ICollection<ProjectMaterial> ProjectMaterials { get; set; }
    }
}