// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("ProjectScopeProgress")]
    public partial class ProjectScopeProgress
    {
        public int Id { get; set; }
        public int? ProjectScopeId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Progress { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ProgressDate { get; set; }

        [ForeignKey("ProjectScopeId")]
        [InverseProperty("ProjectScopeProgresses")]
        public virtual ProjectScope ProjectScope { get; set; }
    }
}