// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("ProjectSite")]
    public partial class ProjectSite
    {
        public ProjectSite()
        {
            ProjectMaterials = new HashSet<ProjectMaterial>();
            ProjectScopes = new HashSet<ProjectScope>();
        }

        public int Id { get; set; }
        [Column("POId")]
        public int? Poid { get; set; }
        public int? SiteId { get; set; }
        public int? StageId { get; set; }
        public int? TeamLeaderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActualStartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActualEndDate { get; set; }
        [Column(TypeName = "text")]
        public string Remarks { get; set; }

        [ForeignKey("Poid")]
        [InverseProperty("ProjectSites")]
        public virtual ProjectMaster Po { get; set; }
        [ForeignKey("SiteId")]
        [InverseProperty("ProjectSites")]
        public virtual Site Site { get; set; }
        [ForeignKey("StageId")]
        [InverseProperty("ProjectSites")]
        public virtual Stage Stage { get; set; }
        [ForeignKey("TeamLeaderId")]
        [InverseProperty("ProjectSites")]
        public virtual TeamLeader TeamLeader { get; set; }
        [InverseProperty("Site")]
        public virtual ICollection<ProjectMaterial> ProjectMaterials { get; set; }
        [InverseProperty("Posite")]
        public virtual ICollection<ProjectScope> ProjectScopes { get; set; }
    }
}