// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    public partial class Site
    {
        public Site()
        {
            Boqentries = new HashSet<Boqentry>();
            DesignRepos = new HashSet<DesignRepo>();
            ProjectSites = new HashSet<ProjectSite>();
            Rta = new HashSet<Rtum>();
        }

        public int Id { get; set; }
        public string SiteId { get; set; }
        public string SiteName { get; set; }
        public string Homing { get; set; }
        public string Brgy { get; set; }
        [Column("POId")]
        public string Poid { get; set; }
        public bool Active { get; set; }
        public bool SiteClose { get; set; }

        [InverseProperty("Sited")]
        public virtual ICollection<Boqentry> Boqentries { get; set; }
        [InverseProperty("Site")]
        public virtual ICollection<DesignRepo> DesignRepos { get; set; }
        [InverseProperty("Site")]
        public virtual ICollection<ProjectSite> ProjectSites { get; set; }
        [InverseProperty("Site")]
        public virtual ICollection<Rtum> Rta { get; set; }
    }
}