// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("Status")]
    public partial class Status
    {
        public Status()
        {
            ProjectMasters = new HashSet<ProjectMaster>();
        }

        public int Id { get; set; }
        public string StatusName { get; set; }

        [InverseProperty("Status")]
        public virtual ICollection<ProjectMaster> ProjectMasters { get; set; }
    }
}