// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("TeamLeader")]
    public partial class TeamLeader
    {
        public TeamLeader()
        {
            ProjectSites = new HashSet<ProjectSite>();
        }

        public int Id { get; set; }
        public string Fullname { get; set; }

        [InverseProperty("TeamLeader")]
        public virtual ICollection<ProjectSite> ProjectSites { get; set; }
    }
}