// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorCableReel.Server.Models
{
    [Table("UOM")]
    public partial class Uom
    {
        public Uom()
        {
            ProjectMaterials = new HashSet<ProjectMaterial>();
            ProjectScopes = new HashSet<ProjectScope>();
        }

        public int Id { get; set; }
        public string UomName { get; set; }

        [InverseProperty("Uom")]
        public virtual ICollection<ProjectMaterial> ProjectMaterials { get; set; }
        [InverseProperty("Uom")]
        public virtual ICollection<ProjectScope> ProjectScopes { get; set; }
    }
}