// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Shared.Models
{
    
    public partial class Boqentry
    {
        public int Id { get; set; }
        public int? MatId { get; set; }
        public int? Qty { get; set; }
        public int? SitedId { get; set; }

    }
}