// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Shared.Models
{
   
    public partial class Boqsetup
    {
        public int Id { get; set; }
        public int MatId { get; set; }
        public int? Quantifier { get; set; }
        public int? ParentMatId { get; set; }

     
    }
}