// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Shared.Models
{
   
    public partial class DesignRepo
    {
        public int Id { get; set; }
        public int? SiteId { get; set; }
        public string Location { get; set; }
        public int? Revision { get; set; }
       
        public DateTime? CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }

       
    }
}