// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Shared.Models
{
    public partial class Material
    {


        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }

    }
}