// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Server.Models
{
    
    public partial class ProjectScopeProgress
    {
        public int Id { get; set; }
        public int? ProjectScopeId { get; set; }
      
        public decimal? Progress { get; set; }
      
        public DateTime? ProgressDate { get; set; }

      
    }
}