// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCableReel.Shared.Models
{
    public partial class ProjectMaterial
    {
        public int Id { get; set; }
        public int? SiteId { get; set; }
        public string RefNo { get; set; }
        public int? MaterialId { get; set; }
        public int? UomId { get; set; }
        public int? EstQty { get; set; }
        public int? ActualQty { get; set; }
        public int? Variance { get; set; }
        public int? Used { get; set; }
        public int? ForReturn { get; set; }
        public Guid? CreatedBy { get; set; }
      
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
       
        public DateTime? LastUpdate { get; set; }

      
    }
}