// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCableReel.Shared.Models
{
    
    public partial class ProjectMaster
    {
       
        public int Id { get; set; }
      
        public string Ponumber { get; set; }
        public string Description { get; set; }
        public int ClientId { get; set; }
        public int ProjectTypeId { get; set; }
        public int StatusId { get; set; }
       
        public DateTime CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
      
        public DateTime? LastUpdate { get; set; }
        public Guid? UpdatedBy { get; set; }

     
    }
}