// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Shared.Models
{

    public partial class ProjectType
    {


        public int Id { get; set; }

        public string ProjectType1 { get; set; }

    }
}