// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCableReel.Shared.Models
{
  
    public partial class ProjectSite
    {
     
        public int Id { get; set; }
      
        public int? Poid { get; set; }
        public int? SiteId { get; set; }
        public int? StageId { get; set; }
        public int? TeamLeaderId { get; set; }
      
        public DateTime? StartDate { get; set; }
      
        public DateTime? EndDate { get; set; }
      
        public DateTime? ActualStartDate { get; set; }
       
        public DateTime? ActualEndDate { get; set; }
      
        public string Remarks { get; set; }

    }
}