// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Shared.Models
{

    public partial class ProjectScope
    {
      
        public int Id { get; set; }
       
        public int? PositeId { get; set; }
        public int? ScopeId { get; set; }
        public int? UomId { get; set; }
    
        public decimal? EstQtyLength { get; set; }
  
        public decimal? ActQtyLength { get; set; }

     
    }
}