// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace BlazorCableReel.Shared.Models
{
 
    public partial class Rtum
    {
        public int Id { get; set; }
        public int? SiteId { get; set; }
        public int? SeqNo { get; set; }
        public string PoleTag { get; set; }
    
        public string Coordinates { get; set; }
    
        public string Location { get; set; }
        public bool? Nap { get; set; }
        public bool? Lcp { get; set; }
        public bool? Arm { get; set; }
     
        public string Remarks { get; set; }
        public string PolePic { get; set; }
        public string PoleTagPic { get; set; }
   
        public DateTime? CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }

   
    }
}