// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCableReel.Shared.Models
{

    public partial class Scope
    {
       
        public int Id { get; set; }
        public string ScopeName { get; set; }

    }
}