// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BlazorCableReel.Shared.Models
{
    public partial class Site
    {
       

        public int Id { get; set; }
        [Required]
        public string SiteId { get; set; }
        [Required]
        public string SiteName { get; set; }
        public string Homing { get; set; }
        public string Brgy { get; set; }
        
        public string Poid { get; set; }
        public bool Active { get; set; }
        public bool SiteClose { get; set; }

     
    }
}