// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCableReel.Server.Models
{
   
    public partial class TeamLeader
    {
     

        public int Id { get; set; }
        public string Fullname { get; set; }

      
    }
}